#!/bin/bash

for f in `cat file_list.txt`; do
   wget ${f};
done;

for f in *.tar; do
  tar -xvf ${f};
done;


# list the directories and upload them to keep order on the HDFS
# listing dirs from https://stackoverflow.com/questions/14352290/listing-only-directories-using-ls-in-bash
for f in `ls -d */ `; do
  hdfs dfs -put ${f} /project/core/openaire_funders/;
done;

